name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.3

      - name: List all modified files
        run: |
          declare -A folders
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do          
            echo "$file was modified"
            folders[$(dirname "$file")]="."            
          done
          post_folders=()
          for x in "${!folders[@]}"; do
            if [ -f "$x/metadata.json" ]; then
              post_folders+=($x)
              echo "Post folder $x"
            fi            
          done      
          echo ::set-output name=folders::${post_folders[@]}

      - name: List folders
        run: |
          echo ${{ steps.vars.outputs.folders }}
          
      - name: Versions
        run: |
          bash --version
          curl --version
          jq --version
      
